# Generated by Django 5.0.7 on 2024-08-01 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_libraryvisitor_visitor_alter_visitor_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_librarian',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_visitor',
        ),
    ]
