# Generated by Django 5.0.7 on 2024-07-31 20:20

import src.core.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='fullname',
        ),
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=src.core.utils.MultiSelectField(choices=[('fantasy', 'Фантастика'), ('adventure', 'Приключения'), ('detective', 'Детектив'), ('horror', 'Ужасы'), ('thriller', 'Триллер'), ('mysticism', 'Мистика'), ('action', 'Боевик')], max_length=500),
        ),
    ]
