# Generated by Django 5.0.7 on 2024-08-02 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_name_author_fullname_alter_book_genres'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['name'], 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
    ]
