# Generated by Django 5.0.7 on 2024-08-04 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_customuserbook_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuserbook',
            options={'ordering': ['book__name'], 'verbose_name': 'CustomUserBook', 'verbose_name_plural': 'CustomUserBooks'},
        ),
        migrations.RemoveField(
            model_name='customuserbook',
            name='date_return',
        ),
    ]
