# Generated by Django 5.0.7 on 2024-08-06 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_historicalbook_historicalcustomuserbook'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['-id'], 'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['name'], 'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='customuserbook',
            options={'ordering': ['book__name'], 'verbose_name': 'Книга на руках', 'verbose_name_plural': 'Книги на руках'},
        ),
        migrations.AlterModelOptions(
            name='historicalbook',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Книга', 'verbose_name_plural': 'historical Книги'},
        ),
        migrations.DeleteModel(
            name='HistoricalCustomUserBook',
        ),
    ]
