# Generated by Django 5.0.7 on 2024-08-06 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_author_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalBook',
        ),
    ]
